# Generated by Django 4.2.2 on 2023-07-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg',
            field=models.ImageField(default='bgDefault', upload_to='bg_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
