# Generated by Django 4.2.2 on 2023-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_bg_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg',
            field=models.ImageField(upload_to='bg_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pp',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
